name: elf2hunk

on:
  push:
    paths:
      - "ci/elf2hunk/**"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ci/elf2hunk/clone.sh
      - run: ci/elf2hunk/build.sh
      - run: ci/elf2hunk/archive-linux.sh
      - uses: actions/upload-artifact@v3
        with:
          name: elf2hunk-linux
          path: elf2hunk-linux.tar

  macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: ci/elf2hunk/clone.sh
      - run: ci/elf2hunk/build.sh
      - run: ci/elf2hunk/archive-macos.sh
      - uses: actions/upload-artifact@v3
        with:
          name: elf2hunk-macos
          path: elf2hunk-macos.tar
